### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by coolrc136** [echo724/notion2md#2]
```
$ python3 -m notion2md
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/notion2md/__init__.py", line 1, in <module>
    from .export_manager import export_cli
  File "/usr/local/lib/python3.8/dist-packages/notion2md/export_manager.py", line 5, in <module>
    from notion2md.exporter import PageBlockExporter
  File "/usr/local/lib/python3.8/dist-packages/notion2md/exporter.py", line 345
    """This function will get inline math code and append it to the text
"""
    ^
IndentationError: expected an indented block
```

fix: add four spaces before `notion2md/exporter.py` line 345 and 346：

**Comment by echo724** [comment]
Hi Thank you for notifying me the error. I fixed it and try update the `notion2md` by pip.

Thank you
